import React from 'react'
import { Routes, Route } from 'react-router-dom'
import Nav from './components/Nav.jsx'
import Footer from './components/Footer.jsx'
import Home from './pages/Home.jsx'
import UsersPage from './pages/UsersPage.jsx'
import UserForm from './pages/UserForm.jsx'
import ProductsPage from './pages/ProductsPage.jsx'
import ProductForm from './pages/ProductForm.jsx'
import BillsPage from './pages/BillsPage.jsx'
import BillForm from './pages/BillForm.jsx'
import CategoriesPage from './pages/CategoriesPage.jsx'
import CategoryForm from './pages/CategoryForm.jsx'
export default function App(){ return (<div className="flex flex-col min-h-screen"><Nav/><main className="flex-1 container mx-auto p-4"><Routes><Route path="/" element={<Home/>}/><Route path="/users" element={<UsersPage/>}/><Route path="/users/new" element={<UserForm/>}/><Route path="/users/:id" element={<UserForm/>}/><Route path="/products" element={<ProductsPage/>}/><Route path="/products/new" element={<ProductForm/>}/><Route path="/products/:id" element={<ProductForm/>}/><Route path="/bills" element={<BillsPage/>}/><Route path="/bills/new" element={<BillForm/>}/><Route path="/bills/:id" element={<BillForm/>}/><Route path="/categories" element={<CategoriesPage/>}/><Route path="/categories/new" element={<CategoryForm/>}/><Route path="/categories/:id" element={<CategoryForm/>}/></Routes></main><Footer/></div>) }